---
booktitle: Proceedings of Machine Learning Research
volume: 89
year: '2019'
start: 2019-04-16
end: 2019-04-18
published: 2019-04-11
url: http://proceedings.mlr.press
location: Naha, Okinawa, Japan
shortname: AISTATS
layout: proceedings
series: Proceedings of Machine Learning Research
id: AISTATS-2019
month: 0
cycles: false
bibtex_editor: Chaudhuri, Kamalika and Sugiyama, Masashi
editor:
- given: Kamalika
  family: Chaudhuri
- given: Masashi
  family: Sugiyama
title: Proceedings of Machine Learning Research
description: |
  Proceedings of Machine Learning Research on 16-18 April 2019

  Published as Volume 89 by the Proceedings of Machine Learning Research on 11 April 2019.

  Volume Edited by:
    Kamalika Chaudhuri
    Masashi Sugiyama

  Series Editors:
    Neil D. Lawrence
    Mark Reid
date_str: 16--18 Apr
baseurl: "/v89"
twitter_username: MLResearchPress
github_username: mlresearch
markdown: kramdown
permalink: "/:title.html"
github:
  edit: true
  repository: v89
display:
  copy_button:
    bibtex: true
    endnote: true
    apa: true
  comments: false
email: ''
conference:
  name: The 22nd International Conference on Artificial Intelligence and Statistics
  url: 
  location: ''
  dates:
  - 2019-04-16
  - 2019-04-17
  - 2019-04-18
analytics:
  google:
    tracking_id: UA-92432422-1
# Site settings
# Auto generated from /Users/neil/mlresearch/v89/AISTATS2019.bib
